version: "2"
x-environment: &env
  - CELERY_BROKER_URL=redis://redis:6379/0
  - CELERY_RESULT_BACKEND=redis://redis:6379/0
  - ACCESS_KEY=minioadmin
  - SECRET_KEY=minioadmin
  - ENDPOINT=minio:9000
  - BUCKET=data

services:
  inswapper:
    build:
      context: ./InswapperService
      dockerfile: app.dockerfile
    command: uvicorn main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - app-volume:/usr/src/app/
    environment: *env

  worker:
    build:
      context: ./InswapperService
      dockerfile: app.dockerfile
    command: [ "celery", "-A", "worker", "worker", "-l", "info", "--max-tasks-per-child", "1", "--autoscale=5,1", "--concurrency", "1" ]
    environment: *env
    depends_on:
      - inswapper
      - redis
    volumes:
      - app-volume:/usr/src/app/

    
  api:
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    environment:
      - "API=http://inswapper:8000"
    depends_on:
      - inswapper
    ports:
      - "3000:3000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /data

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    expose:
      - 6379

volumes:
  app-volume:
  minio_storage: {}