version: "2"
x-environment: &env
  - CELERY_BROKER_URL=redis://redis:6379/0
  - CELERY_RESULT_BACKEND=redis://redis:6379/0
  - ACCESS_KEY=minioadmin
  - SECRET_KEY=minioadmin
  - ENDPOINT=minio:9000
  - BUCKET=data

services:
  inswapper:
    image: just1ce/inswapper-py-api:1.0.0
    deploy:
      replicas: 5
    networks:
      - app-net
    build:
      context: ./InswapperService
      dockerfile: app.dockerfile
    command: uvicorn main:app --host 0.0.0.0
    restart: unless-stopped
    environment: *env
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 192.168.0.2:24224
        tag: default.inswapper

  worker:
    image: just1ce/inswapper-py-worker:1.0.0
    networks:
      - app-net
    build:
      context: ./InswapperService
      dockerfile: worker.dockerfile
    command: [ "celery", "-A", "worker", "worker", "-l", "info", "--pool=solo" ]
    deploy:
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-f9cff33c-ece4-3307-cbd0-bdb67207374f"]
              capabilities: [gpu]
    environment: *env
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 192.168.0.2:24224
        tag: default.inswapper-worker
  worker1:
    image: just1ce/inswapper-py-worker:1.0.0
    networks:
      - app-net
    build:
      context: ./InswapperService
      dockerfile: worker.dockerfile
    command: [ "celery", "-A", "worker", "worker", "-l", "info", "--pool=solo" ]
    deploy:
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-a521bc92-5850-6584-71a8-6645cd13e3c1"]
              capabilities: [gpu]
    environment: *env
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 192.168.0.2:24224
        tag: default.inswapper-worker
  worker2:
    image: just1ce/inswapper-py-worker:1.0.0
    networks:
      - app-net
    build:
      context: ./InswapperService
      dockerfile: worker.dockerfile
    command: [ "celery", "-A", "worker", "worker", "-l", "info", "--pool=solo" ]
    deploy:
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-351599a6-27b4-7eb3-2e4c-554a9bddee44"]
              capabilities: [gpu]
    environment: *env
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 192.168.0.2:24224
        tag: default.inswapper-worker
  worker3:
    image: just1ce/inswapper-py-worker:1.0.0
    networks:
      - app-net
    build:
      context: ./InswapperService
      dockerfile: worker.dockerfile
    command: [ "celery", "-A", "worker", "worker", "-l", "info", "--pool=solo" ]
    deploy:
      replicas: 4
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["GPU-aec529fe-704e-c6bd-28d4-b8ed5ab1c718"]
              capabilities: [gpu]
    environment: *env
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 192.168.0.2:24224
        tag: default.inswapper-worker
  api:
    image: just1ce/inswapper-api-gateway:1.0.0
    deploy:
      replicas: 5
    networks:
      - app-net
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    env_file:
      - .env
    environment:
      - API=http://inswapper:8000
      - MONGO=mongodb://root:example@mongo:27017/
      - ACCESS_KEY=minioadmin
      - SECRET_KEY=minioadmin
      - ENDPOINT=minio
      - PORT=9000
      - BUCKET=data
      - PREFIX=base-images
    restart: unless-stopped
    logging:
      driver: 'fluentd'
      options:
        fluentd-address: 192.168.0.2:24224
        tag: json.api

networks:
  app-net:
    external: true

