version: "2"
x-environment: &env
  - CELERY_BROKER_URL=redis://redis:6379/0
  - CELERY_RESULT_BACKEND=redis://redis:6379/0
  - ACCESS_KEY=minioadmin
  - SECRET_KEY=minioadmin
  - ENDPOINT=minio:9000
  - BUCKET=data

services:
  inswapper:
    image: just1ce/inswapper-py-api:1.0.0
    build:
      context: ./InswapperService
      dockerfile: app.dockerfile
    command: uvicorn main:app --host 0.0.0.0
    restart: unless-stopped
    volumes:
      - tmp-images-volume:/usr/src/app/tmp/
    environment: *env

  worker:
    image: just1ce/inswapper-py-worker:1.0.0
    build:
      context: ./InswapperService
      dockerfile: worker.dockerfile
    command: [ "celery", "-A", "worker", "worker", "-l", "info", "--pool=solo" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment: *env
    restart: unless-stopped
    volumes:
      - ./InswapperService:/usr/src/app
      - tmp-images-volume:/usr/src/app/tmp/

  api:
    image: just1ce/inswapper-api-gateway:1.0.0
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    env_file:
      - .env
    environment:
      - API=http://inswapper:8000
      - MONGO=mongodb://root:example@mongo:27017/
      - ACCESS_KEY=minioadmin
      - SECRET_KEY=minioadmin
      - ENDPOINT=minio
      - PORT=9000
      - BUCKET=data
      - PREFIX=images
    restart: unless-stopped

volumes:
  tmp-images-volume:

