version: "2"

services:
  minio:
    image: minio/minio
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - minio_storage:/data
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /data
  cdn:
    image: nginxinc/nginx-s3-gateway:latest-20231222
    restart: unless-stopped
    environment:
      ALLOW_DIRECTORY_LIST: "false"
      AWS_SIGS_VERSION: 2
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      S3_BUCKET_NAME: data
      S3_REGION: us-east-1
      S3_SERVER_PORT: 9000
      S3_SERVER_PROTO: http
      S3_SERVER: minio
      S3_STYLE: path
      PROXY_CACHE_MAX_SIZE: 1g
  reverse-proxy:
    image: just1ce/inswapper-reverse-proxy:1.0.0
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    build:
      context: ./reverse-proxy-nginx
      dockerfile: ./dockerfile
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    volumes:
      - redis-volume:/data
    expose:
      - 6379

  mongo:
    image: mongo
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_storage:/data
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  redis-volume:
  minio_storage:
  mongo_storage:
