# prometheus.yml
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'slave-prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'slave-node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'slave-process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
  - job_name: 'slave-nvidia-exporter'
    static_configs:
      - targets: ['nvidia-smi-exporter:9835']
