# prometheus.yml
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9913']
  - job_name: 'process-exporter'
    static_configs:
      - targets: ['process-exporter:9256']
  - job_name: 'celery-exporter'
    static_configs:
      - targets: ['celery-exporter:9808']
  - job_name: 'nvidia-exporter'
    static_configs:
      - targets: ['nvidia-smi-exporter:9835']
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
        - '172.19.0.188:9090'
